# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      **/TestUpdaterAnalyzers.csproj
      **/TestUpdaterAnalyzers.Test.csproj
      **/NXunitConverterAnalyzer.csproj
      **/NXunitConverterAnalyzer.Test.csproj
    arguments: '-c Debug'
  displayName: dotnet build

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.Test.csproj'
  displayName: dotnet test

